spring:
  rsocket:
    server:
      transport: websocket
      mapping-path: /

amazon:
  aws:
    access-key: "test-key"
    secret-key: "test-secret"
  dynamo-db:
    endpoint: http://localhost:8000
    region: us-east-1

test:
  id: 1
  greeting: Hello

firebase:
  api-url: https://fcm.googleapis.com/fcm/send

management:
  server:
    port: 8081